# Generated by Django 4.0.3 on 2022-03-29 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('contact_number', models.CharField(max_length=16, unique=True)),
                ('credit_card', models.CharField(max_length=20, null=True, unique=True)),
                ('billing_address', models.CharField(max_length=50, unique=True)),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=4)),
                ('brand_name', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=20)),
                ('serial_number', models.CharField(max_length=20, unique=True)),
                ('current_location', models.CharField(max_length=50)),
                ('daily_rate', models.CharField(max_length=20)),
                ('available', models.CharField(max_length=20)),
                ('registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('contact_number', models.CharField(max_length=16, unique=True)),
                ('credit_card', models.CharField(max_length=20, unique=True)),
                ('billing_address', models.CharField(max_length=50, unique=True)),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ordered', models.DateTimeField(auto_now_add=True)),
                ('delivery_location', models.CharField(max_length=64)),
                ('delivery_date', models.DateField(blank=True)),
                ('return_date', models.DateField(blank=True)),
                ('notes', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rentals.customer')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rentals.equipment')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rentals.renter'),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('contact_number', models.CharField(max_length=16, unique=True)),
                ('credit_card', models.CharField(max_length=20, unique=True)),
                ('billing_address', models.CharField(max_length=50, unique=True)),
                ('vin_number', models.CharField(default=None, max_length=20)),
                ('available', models.CharField(max_length=20)),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('delivery_location', models.CharField(max_length=64)),
                ('delivery_date', models.DateField(blank=True)),
                ('return_date', models.DateField(blank=True)),
                ('notes', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rentals.customer')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rentals.driver')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rentals.equipment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rentals.order')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rentals.renter')),
            ],
        ),
    ]
